In [30]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [42]:
mosquito_df = pd.read_csv('C:/Users/LG/Desktop/data.csv',encoding='UTF-8-sig')
mosquito_df

,ID,Date,Mean Temperature(°C),Minimum Temperature(°C),Maximum Temperature(°C),Precipitation(mm),Maximum wind speed(m/s),Mean Wind Speed (m/s),Minimum Relative Humidity(%),Mean Relative Humidity(%),Duration of Sunshine(hr),Mean Surface Temperature(°C),Minimum Grass Temperature(°C),Cumulative Precipitation (mm),Mosquito Value
0,1,2021-09-27,21.6,18.7,25.0,0.0,6.6,2.4,52.0,66.0,2.2,21.6,16.1,0.0,63.1
1,2,2021-09-26,22.6,18.4,27.3,0.0,7.2,2.3,50.0,63.0,8.3,23.9,14.6,0.0,70.2
2,3,2021-09-25,21.2,18.7,23.1,0.0,6.4,2.3,66.0,72.6,0.0,21.1,14.3,0.0,70.5
3,4,2021-09-24,21.8,16.7,26.9,0.0,6.9,2.2,46.0,67.5,9.9,23.1,12.1,0.0,70.5
4,5,2021-09-23,20.9,16.9,25.9,0.0,10.9,2.4,48.0,67.3,8.0,22.7,11.9,0.0,63.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1065,1066,2016-05-05,18.9,10.2,26.9,7.5,6.6,1.7,17.0,50.8,10.9,20.0,3.6,17.0,24.4
1066,1067,2016-05-04,15.7,10.2,20.6,0.0,18.0,5.1,28.0,46.6,12.8,16.6,8.9,0.0,25.6
1067,1068,2016-05-03,12.9,8.9,17.6,27.0,17.5,4.9,72.0,86.1,0.0,14.8,8.5,27.0,30.4
1068,1069,2016-05-02,21.1,16.5,28.4,16.5,8.2,2.2,33.0,64.5,7.5,24.4,12.1,43.5,27.4
1069,1070,2016-05-01,18.8,12.2,26.0,0.0,9.8,2.2,16.0,40.5,6.8,20.2,5.7,0.0,25.4

In [43]:
mosquito_df = mosquito_df.dropna()# Null값 제거

In [44]:
mosquito_df= mosquito_df.drop(['ID'],axis='columns') # 필요없는 column제거

In [45]:
mosquito_df

,Date,Mean Temperature(°C),Minimum Temperature(°C),Maximum Temperature(°C),Precipitation(mm),Maximum wind speed(m/s),Mean Wind Speed (m/s),Minimum Relative Humidity(%),Mean Relative Humidity(%),Duration of Sunshine(hr),Mean Surface Temperature(°C),Minimum Grass Temperature(°C),Cumulative Precipitation (mm),Mosquito Value
0,2021-09-27,21.6,18.7,25.0,0.0,6.6,2.4,52.0,66.0,2.2,21.6,16.1,0.0,63.1
1,2021-09-26,22.6,18.4,27.3,0.0,7.2,2.3,50.0,63.0,8.3,23.9,14.6,0.0,70.2
2,2021-09-25,21.2,18.7,23.1,0.0,6.4,2.3,66.0,72.6,0.0,21.1,14.3,0.0,70.5
3,2021-09-24,21.8,16.7,26.9,0.0,6.9,2.2,46.0,67.5,9.9,23.1,12.1,0.0,70.5
4,2021-09-23,20.9,16.9,25.9,0.0,10.9,2.4,48.0,67.3,8.0,22.7,11.9,0.0,63.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1065,2016-05-05,18.9,10.2,26.9,7.5,6.6,1.7,17.0,50.8,10.9,20.0,3.6,17.0,24.4
1066,2016-05-04,15.7,10.2,20.6,0.0,18.0,5.1,28.0,46.6,12.8,16.6,8.9,0.0,25.6
1067,2016-05-03,12.9,8.9,17.6,27.0,17.5,4.9,72.0,86.1,0.0,14.8,8.5,27.0,30.4
1068,2016-05-02,21.1,16.5,28.4,16.5,8.2,2.2,33.0,64.5,7.5,24.4,12.1,43.5,27.4
1069,2016-05-01,18.8,12.2,26.0,0.0,9.8,2.2,16.0,40.5,6.8,20.2,5.7,0.0,25.4

In [46]:
mosquito_df.describe()

,Mean Temperature(°C),Minimum Temperature(°C),Maximum Temperature(°C),Precipitation(mm),Maximum wind speed(m/s),Mean Wind Speed (m/s),Minimum Relative Humidity(%),Mean Relative Humidity(%),Duration of Sunshine(hr),Mean Surface Temperature(°C),Minimum Grass Temperature(°C),Cumulative Precipitation (mm),Mosquito Value
count,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000
mean,22.496821,18.538054,27.241522,5.405684,8.165703,2.068882,44.933526,65.662909,6.731696,24.999711,15.396628,13.480732,50.394412
std,4.741259,5.321513,4.716000,16.144167,2.295679,0.626716,16.113161,13.697546,4.327240,5.646309,6.225118,40.200050,26.462500
min,5.700000,0.700000,8.200000,0.000000,3.900000,0.700000,7.000000,23.800000,0.000000,6.000000,-5.900000,0.000000,0.000000
25%,19.500000,14.900000,24.300000,0.000000,6.700000,1.625000,34.000000,57.100000,2.500000,21.600000,11.225000,0.000000,29.400000
50%,23.000000,19.100000,27.600000,0.000000,7.700000,2.000000,43.000000,65.400000,7.500000,25.400000,16.000000,0.000000,51.400000
75%,25.700000,22.600000,30.200000,1.500000,9.100000,2.400000,54.000000,74.500000,10.500000,28.900000,20.400000,2.975000,70.800000
max,33.700000,30.300000,39.600000,144.500000,28.300000,6.000000,94.000000,98.100000,13.700000,40.100000,26.800000,325.500000,106.800000

In [48]:
mosquito_df.corrwith(mosquito_df['Mosquito Value'])

Mean Temperature(°C)             0.457187
Minimum Temperature(°C)          0.509301
Maximum Temperature(°C)          0.353309
Precipitation(mm)                0.143756
Maximum wind speed(m/s)          0.028199
Mean Wind Speed (m/s)            0.108794
Minimum Relative Humidity(%)     0.395072
Mean Relative Humidity(%)        0.361955
Duration of Sunshine(hr)        -0.248623
Mean Surface Temperature(°C)     0.389461
Minimum Grass Temperature(°C)    0.519614
Cumulative Precipitation (mm)    0.233390
Mosquito Value                   1.000000
dtype: float64

In [49]:
mosquito_df = mosquito_df.drop(['Maximum wind speed(m/s)'],axis='columns') 
# 무의미한 상관관계 가지는 feature 삭제

In [50]:
mosquito_df.to_csv('C:/Users/LG/Desktop/result.csv')